// <auto-generated /> — golden fixture: a realistic EF-generated ModelSnapshot exercising the
// string-based fluent forms (Entity("Ns.T"), Property<T>("Name"), HasKey("A","B"),
// HasOne(...).WithMany(...).HasForeignKey(...)), annotation noise, a second per-entity pass for
// relationships, and a nested OwnsOne builder block.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SnapFx.Migrations
{
    [DbContext(typeof(JournalContext))]
    partial class JournalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("SnapFx.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'unrated'");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("SnapFx.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("SnapFx.ShipmentItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.ToTable("ShipmentItems");
                });

            modelBuilder.Entity("SnapFx.Entry", b =>
                {
                    b.HasOne("SnapFx.Journal", "Journal")
                        .WithMany("Entries")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("SnapFx.Journal", b =>
                {
                    b.OwnsOne("SnapFx.GeoTag", "Location", b1 =>
                        {
                            b1.Property<int>("JournalId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("JournalId");

                            b1.ToTable("Journals");

                            b1.WithOwner()
                                .HasForeignKey("JournalId");
                        });

                    b.Navigation("Entries");

                    b.Navigation("Location");
                });
        }
    }
}
