// <auto-generated /> — golden fixture: a realistic EF-generated ModelSnapshot for a one-to-one
// relationship. The snapshot generator emits the two-string HasForeignKey overload
// (HasForeignKey("Snap.LedgerHeader", "LedgerId")) whose first argument is the dependent entity
// type name, not an FK property — it must not be fabricated into a phantom column on LedgerHeader.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Snap.Migrations
{
    [DbContext(typeof(LedgerContext))]
    partial class LedgerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Snap.Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ledgers");
                });

            modelBuilder.Entity("Snap.LedgerHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LedgerId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId")
                        .IsUnique();

                    b.ToTable("LedgerHeaders");
                });

            modelBuilder.Entity("Snap.LedgerHeader", b =>
                {
                    b.HasOne("Snap.Ledger", "Ledger")
                        .WithOne("Header")
                        .HasForeignKey("Snap.LedgerHeader", "LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("Snap.Ledger", b =>
                {
                    b.Navigation("Header");
                });
        }
    }
}
