<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>projgraph</ToolCommandName>
    <Description>CLI tool to visualize project dependencies and generate graphs.</Description>
    <PackageTags>dotnet-tool;graph;dependencies;visualization;mermaid;cli</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjGraph.Lib\ProjGraph.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli"/>
  </ItemGroup>

</Project>
