<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjGraph.Core\ProjGraph.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Buildalyzer" />
    <PackageReference Include="Microsoft.Build" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" />
  </ItemGroup>

</Project>
