<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjGraph.Lib.ProjectGraph\ProjGraph.Lib.ProjectGraph.csproj"/>
    <ProjectReference Include="..\ProjGraph.Lib.EntityFramework\ProjGraph.Lib.EntityFramework.csproj"/>
    <ProjectReference Include="..\ProjGraph.Lib.ClassDiagram\ProjGraph.Lib.ClassDiagram.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
  </ItemGroup>

</Project>
