---
title: JournalContext
---
erDiagram
  Entry {
    int Id PK
    int JournalId FK
    decimal Score "precision(18,2)"
    string Title "required"
  }
  Journal {
    int Id PK
    int JournalId PK
    string City
    string Name "required, max:200"
    string Rating "default:N'unrated"
  }
  ShipmentItem {
    int OrderId PK
    int ProductId PK
    int Quantity
  }
  Journal ||--o{ Entry : ""