<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>projgraph-mcp</ToolCommandName>
    <Description>MCP server for ProjGraph to interact with LLMs and provide project graph context.</Description>
    <PackageTags>dotnet-tool;mcp;llm;context;graph;dependencies</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjGraph.Lib\ProjGraph.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
