<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjGraph.Lib.Core\ProjGraph.Lib.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ProjGraph.Tests.Unit.ClassDiagram"/>
    <InternalsVisibleTo Include="ProjGraph.Tests.Integration.Mcp"/>
  </ItemGroup>

</Project>
