<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjGraph.Lib.Core\ProjGraph.Lib.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" VersionOverride="10.0.3" />
    <InternalsVisibleTo Include="ProjGraph.Tests.Unit.EntityFramework"/>
    <InternalsVisibleTo Include="ProjGraph.Tests.Integration.Mcp"/>
  </ItemGroup>

</Project>
